---
## reference compose file: https://gist.github.com/setekhid/17a7bfb8ac26428ebced829d28f780aa
version: "2"

services:
  etcd3:
    image: quay.io/coreos/etcd:v3.1.7
    restart: always
    networks:
      etcd3_net:
        ipv4_address: 172.19.1.12
    ports:
      - 2379:2379
      - 4001:4001
    environment:
      ETCD_NAME: infra3
      ETCD_INITIAL_CLUSTER: infra1=http://172.19.1.10:4001,infra2=http://172.19.1.11:4001,infra3=http://172.19.1.12:4001
      ETCD_INITIAL_CLUSTER_STATE: new
      ETCD_INITIAL_CLUSTER_TOKEN: etcd-tasting-01
      ETCD_LISTEN_CLIENT_URLS: http://0.0.0.0:2379,http://0.0.0.0:2379
      ETCD_LISTEN_PEER_URLS: http://0.0.0.0:4001
      ETCD_ADVERTISE_CLIENT_URLS: http://172.19.1.12:2379,http://172.19.1.12:4001
      ETCD_INITIAL_ADVERTISE_PEER_URLS: http://172.19.1.12:4001
networks:
  etcd_net:
    ipam:
      driver: default
      config:
        - subnet: 172.19.0.0/16
...