---
# Config  for my application
# --------------------------
# myapp:
#   foo: bar
#   bar: [1, 2]
# Config for logging
# ------------------
# See https://docs.python.org/2.7/library/logging.config.html#configuration-dictionary-schema
logging:
  version: 1
  disable_existing_loggers: true
  # Configuring the default (root) logger is highly recommended
  root:
    level: NOTSET
    handlers: [console]
  loggers:
    # Logging from my application
    ssh_auth:
      level: DEBUG
      handlers: [console, logfile]
      qualname: ssh_auth
      propagate: false
    data:
      level: INFO
      handlers: [console, logfile]
      qualname: data
      propagate: false
  handlers:
    logfile:
      class: logging.handlers.RotatingFileHandler
      filename: /var/log/ssh_auth.log
      maxBytes: 1048576
      backupCount: 3
      formatter: simpleFormatter
      level: NOTSET
    console:
      class: logging.StreamHandler
      stream: ext://sys.stdout
      # formatter: simpleFormatter
      level: NOTSET
  formatters:
    simpleFormatter:
      class: logging.Formatter
      format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
      datefmt: '%d/%m/%Y %H:%M:%S'
