---
- hosts: host1
  gather_facts: false
  become: yes
  tasks:
    - name: Run etcd
      docker_container:
        name: etcd1
        image: quay.io/coreos/etcd
        networks:
          - name: etcd_network
            ipv4_address: 172.19.0.4
        restart_policy: always
        published_ports:
          - 12379:2379
          - 12380:2380
          - 14001:4001
        env:
          ETCD_NAME: infra1
          ETCD_INITIAL_CLUSTER: infra1=http://172.19.0.4:12380,infra2=http://172.19.0.5:22380,infra3=http://172.19.0.6:32380
          ETCD_INITIAL_CLUSTER_STATE: new
          ETCD_INITIAL_CLUSTER_TOKEN: etcd-tasting-01
          ETCD_LISTEN_CLIENT_URLS: http://0.0.0.0:12379,http://0.0.0.0:14001,http://localhost:2379
          ETCD_LISTEN_PEER_URLS: http://0.0.0.0:12380,http://localhost:2380
          ETCD_ADVERTISE_CLIENT_URLS: http://172.19.0.4:12379,http://172.19.0.4:14001
          ETCD_INITIAL_ADVERTISE_PEER_URLS: http://172.19.0.4:12380

- hosts: host1
  gather_facts: false
  become: yes
  tasks:
    - name: Run etcd
      docker_container:
        name: etcd2
        image: quay.io/coreos/etcd
        networks:
          - name: etcd_network
            ipv4_address: 172.19.0.5
        restart_policy: always
        published_ports:
          - 22379:2379
          - 22380:2380
          - 24001:4001
        env:
          ETCD_NAME: infra2
          ETCD_INITIAL_CLUSTER: infra1=http://172.19.0.4:12380,infra2=http://172.19.0.5:22380,infra3=http://172.19.0.6:32380
          ETCD_INITIAL_CLUSTER_STATE: new
          ETCD_INITIAL_CLUSTER_TOKEN: etcd-tasting-01
          ETCD_LISTEN_CLIENT_URLS: http://0.0.0.0:22379,http://0.0.0.0:24001,http://localhost:2379
          ETCD_LISTEN_PEER_URLS: http://0.0.0.0:22380,http://localhost:2380
          ETCD_ADVERTISE_CLIENT_URLS: http://172.19.0.5:22379,http://172.19.0.5:24001
          ETCD_INITIAL_ADVERTISE_PEER_URLS: http://172.19.0.5:22380

- hosts: host1
  gather_facts: false
  become: yes
  tasks:
    - name: Run etcd
      docker_container:
        name: etcd3
        image: quay.io/coreos/etcd
        networks:
          - name: etcd_network
            ipv4_address: 172.19.0.6
        restart_policy: always
        published_ports:
          - 32379:2379
          - 32380:2380
          - 34001:4001
        env:
          ETCD_NAME: infra3
          ETCD_INITIAL_CLUSTER: infra1=http://172.19.0.4:12380,infra2=http://172.19.0.5:22380,infra3=http://172.19.0.6:32380
          ETCD_INITIAL_CLUSTER_STATE: new
          ETCD_INITIAL_CLUSTER_TOKEN: etcd-tasting-01
          ETCD_LISTEN_CLIENT_URLS: http://0.0.0.0:32379,http://0.0.0.0:34001,http://localhost:2379
          ETCD_LISTEN_PEER_URLS: http://0.0.0.0:32380,http://localhost:2380
          ETCD_ADVERTISE_CLIENT_URLS: http://172.19.0.6:32379,http://172.19.0.6:34001
          ETCD_INITIAL_ADVERTISE_PEER_URLS: http://172.19.0.6:32380
